# Generated by Django 3.2.5 on 2021-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='personnel',
            field=models.CharField(choices=[('1', '1명'), ('2', '2명'), ('3', '3명'), ('4', '4명'), ('5', '5명'), ('6', '6명')], default='1', max_length=2),
        ),
    ]
