# Generated by Django 3.2.5 on 2021-08-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0004_auto_20210805_0949'),
        ('commentapp', '0003_alter_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='feedapp.feed'),
        ),
    ]
