# Generated by Django 3.2.5 on 2021-07-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_personnel'),
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='projectapp.project'),
        ),
    ]
