# Generated by Django 3.2.5 on 2021-08-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_feed_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='writer',
        ),
    ]
